# Generated by Django 3.0.4 on 2022-01-18 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleBuy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversor',
            name='local_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='SimpleBuy.Localidade'),
            preserve_default=False,
        ),
    ]
