# Generated by Django 2.2.10 on 2022-01-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleBuy', '0002_inversor_local_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversor',
            name='endereco_inversor',
            field=models.IntegerField(default=0),
        ),
    ]
