# Generated by Django 3.0.4 on 2022-03-02 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleBuy', '0003_inversor_endereco_inversor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametro',
            old_name='leitura',
            new_name='leitura_media',
        ),
    ]
