# Generated by Django 4.0.5 on 2022-06-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleBuy', '0005_alter_inversor_id_alter_localidade_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitura_h',
            name='parametro',
            field=models.FloatField(),
        ),
    ]
