# Generated by Django 4.0.5 on 2022-06-18 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SimpleBuy', '0006_alter_leitura_h_parametro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leitura_h',
            old_name='parametro',
            new_name='parametro_id',
        ),
    ]
