# Generated by Django 3.0.4 on 2022-03-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=200)),
                ('leitura', models.CharField(default='0', max_length=300)),
                ('id_inversor', models.IntegerField()),
            ],
        ),
    ]
