# Generated by Django 3.0.4 on 2022-03-02 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('identificacao_unidade', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='parametro',
            old_name='leitura',
            new_name='leitura_media',
        ),
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leitura', models.IntegerField()),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conn.Parametro')),
            ],
        ),
        migrations.CreateModel(
            name='Inversor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco_inversor', models.IntegerField(default=0)),
                ('nome', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=200)),
                ('local_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conn.Localidade')),
            ],
        ),
        migrations.AlterField(
            model_name='parametro',
            name='id_inversor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conn.Inversor'),
        ),
    ]
